// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file resource/definitions/kubespan/kubespan.proto (package talos.resource.definitions.kubespan, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { NetIP, NetIPPort, NetIPPrefix } from "../../../common/common_pb";
import { file_common_common } from "../../../common/common_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { KubespanPeerState } from "../enums/enums_pb";
import { file_resource_definitions_enums_enums } from "../enums/enums_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file resource/definitions/kubespan/kubespan.proto.
 */
export const file_resource_definitions_kubespan_kubespan: GenFile = /*@__PURE__*/
  fileDesc("CixyZXNvdXJjZS9kZWZpbml0aW9ucy9rdWJlc3Bhbi9rdWJlc3Bhbi5wcm90bxIjdGFsb3MucmVzb3VyY2UuZGVmaW5pdGlvbnMua3ViZXNwYW4i+gEKCkNvbmZpZ1NwZWMSDwoHZW5hYmxlZBgBIAEoCBISCgpjbHVzdGVyX2lkGAIgASgJEhUKDXNoYXJlZF9zZWNyZXQYAyABKAkSFQoNZm9yY2Vfcm91dGluZxgEIAEoCBIlCh1hZHZlcnRpc2Vfa3ViZXJuZXRlc19uZXR3b3JrcxgFIAEoCBILCgNtdHUYBiABKA0SGAoQZW5kcG9pbnRfZmlsdGVycxgHIAMoCRIfChdoYXJ2ZXN0X2V4dHJhX2VuZHBvaW50cxgIIAEoCBIqCg9leHRyYV9lbmRwb2ludHMYCSADKAsyES5jb21tb24uTmV0SVBQb3J0IkkKDEVuZHBvaW50U3BlYxIUCgxhZmZpbGlhdGVfaWQYASABKAkSIwoIZW5kcG9pbnQYAiABKAsyES5jb21tb24uTmV0SVBQb3J0IoIBCgxJZGVudGl0eVNwZWMSJAoHYWRkcmVzcxgBIAEoCzITLmNvbW1vbi5OZXRJUFByZWZpeBIjCgZzdWJuZXQYAiABKAsyEy5jb21tb24uTmV0SVBQcmVmaXgSEwoLcHJpdmF0ZV9rZXkYAyABKAkSEgoKcHVibGljX2tleRgEIAEoCSKNAQoMUGVlclNwZWNTcGVjEh4KB2FkZHJlc3MYASABKAsyDS5jb21tb24uTmV0SVASKAoLYWxsb3dlZF9pcHMYAiADKAsyEy5jb21tb24uTmV0SVBQcmVmaXgSJAoJZW5kcG9pbnRzGAMgAygLMhEuY29tbW9uLk5ldElQUG9ydBINCgVsYWJlbBgEIAEoCSLZAgoOUGVlclN0YXR1c1NwZWMSIwoIZW5kcG9pbnQYASABKAsyES5jb21tb24uTmV0SVBQb3J0Eg0KBWxhYmVsGAIgASgJEkIKBXN0YXRlGAMgASgOMjMudGFsb3MucmVzb3VyY2UuZGVmaW5pdGlvbnMuZW51bXMuS3ViZXNwYW5QZWVyU3RhdGUSFQoNcmVjZWl2ZV9ieXRlcxgEIAEoAxIWCg50cmFuc21pdF9ieXRlcxgFIAEoAxI3ChNsYXN0X2hhbmRzaGFrZV90aW1lGAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBItChJsYXN0X3VzZWRfZW5kcG9pbnQYByABKAsyES5jb21tb24uTmV0SVBQb3J0EjgKFGxhc3RfZW5kcG9pbnRfY2hhbmdlGAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEJ6CitkZXYudGFsb3MuYXBpLnJlc291cmNlLmRlZmluaXRpb25zLmt1YmVzcGFuWktnaXRodWIuY29tL3NpZGVyb2xhYnMvdGFsb3MvcGtnL21hY2hpbmVyeS9hcGkvcmVzb3VyY2UvZGVmaW5pdGlvbnMva3ViZXNwYW5iBnByb3RvMw", [file_common_common, file_google_protobuf_timestamp, file_resource_definitions_enums_enums]);

/**
 * ConfigSpec describes KubeSpan configuration..
 *
 * @generated from message talos.resource.definitions.kubespan.ConfigSpec
 */
export type ConfigSpec = Message<"talos.resource.definitions.kubespan.ConfigSpec"> & {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;

  /**
   * @generated from field: string cluster_id = 2;
   */
  clusterId: string;

  /**
   * @generated from field: string shared_secret = 3;
   */
  sharedSecret: string;

  /**
   * @generated from field: bool force_routing = 4;
   */
  forceRouting: boolean;

  /**
   * @generated from field: bool advertise_kubernetes_networks = 5;
   */
  advertiseKubernetesNetworks: boolean;

  /**
   * @generated from field: uint32 mtu = 6;
   */
  mtu: number;

  /**
   * @generated from field: repeated string endpoint_filters = 7;
   */
  endpointFilters: string[];

  /**
   * @generated from field: bool harvest_extra_endpoints = 8;
   */
  harvestExtraEndpoints: boolean;

  /**
   * @generated from field: repeated common.NetIPPort extra_endpoints = 9;
   */
  extraEndpoints: NetIPPort[];
};

/**
 * Describes the message talos.resource.definitions.kubespan.ConfigSpec.
 * Use `create(ConfigSpecSchema)` to create a new message.
 */
export const ConfigSpecSchema: GenMessage<ConfigSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_kubespan_kubespan, 0);

/**
 * EndpointSpec describes Endpoint state.
 *
 * @generated from message talos.resource.definitions.kubespan.EndpointSpec
 */
export type EndpointSpec = Message<"talos.resource.definitions.kubespan.EndpointSpec"> & {
  /**
   * @generated from field: string affiliate_id = 1;
   */
  affiliateId: string;

  /**
   * @generated from field: common.NetIPPort endpoint = 2;
   */
  endpoint?: NetIPPort;
};

/**
 * Describes the message talos.resource.definitions.kubespan.EndpointSpec.
 * Use `create(EndpointSpecSchema)` to create a new message.
 */
export const EndpointSpecSchema: GenMessage<EndpointSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_kubespan_kubespan, 1);

/**
 * IdentitySpec describes KubeSpan keys and address.
 *
 * Note: IdentitySpec is persisted on disk in the STATE partition,
 * so YAML serialization should be kept backwards compatible.
 *
 * @generated from message talos.resource.definitions.kubespan.IdentitySpec
 */
export type IdentitySpec = Message<"talos.resource.definitions.kubespan.IdentitySpec"> & {
  /**
   * @generated from field: common.NetIPPrefix address = 1;
   */
  address?: NetIPPrefix;

  /**
   * @generated from field: common.NetIPPrefix subnet = 2;
   */
  subnet?: NetIPPrefix;

  /**
   * @generated from field: string private_key = 3;
   */
  privateKey: string;

  /**
   * @generated from field: string public_key = 4;
   */
  publicKey: string;
};

/**
 * Describes the message talos.resource.definitions.kubespan.IdentitySpec.
 * Use `create(IdentitySpecSchema)` to create a new message.
 */
export const IdentitySpecSchema: GenMessage<IdentitySpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_kubespan_kubespan, 2);

/**
 * PeerSpecSpec describes PeerSpec state.
 *
 * @generated from message talos.resource.definitions.kubespan.PeerSpecSpec
 */
export type PeerSpecSpec = Message<"talos.resource.definitions.kubespan.PeerSpecSpec"> & {
  /**
   * @generated from field: common.NetIP address = 1;
   */
  address?: NetIP;

  /**
   * @generated from field: repeated common.NetIPPrefix allowed_ips = 2;
   */
  allowedIps: NetIPPrefix[];

  /**
   * @generated from field: repeated common.NetIPPort endpoints = 3;
   */
  endpoints: NetIPPort[];

  /**
   * @generated from field: string label = 4;
   */
  label: string;
};

/**
 * Describes the message talos.resource.definitions.kubespan.PeerSpecSpec.
 * Use `create(PeerSpecSpecSchema)` to create a new message.
 */
export const PeerSpecSpecSchema: GenMessage<PeerSpecSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_kubespan_kubespan, 3);

/**
 * PeerStatusSpec describes PeerStatus state.
 *
 * @generated from message talos.resource.definitions.kubespan.PeerStatusSpec
 */
export type PeerStatusSpec = Message<"talos.resource.definitions.kubespan.PeerStatusSpec"> & {
  /**
   * @generated from field: common.NetIPPort endpoint = 1;
   */
  endpoint?: NetIPPort;

  /**
   * @generated from field: string label = 2;
   */
  label: string;

  /**
   * @generated from field: talos.resource.definitions.enums.KubespanPeerState state = 3;
   */
  state: KubespanPeerState;

  /**
   * @generated from field: int64 receive_bytes = 4;
   */
  receiveBytes: bigint;

  /**
   * @generated from field: int64 transmit_bytes = 5;
   */
  transmitBytes: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp last_handshake_time = 6;
   */
  lastHandshakeTime?: Timestamp;

  /**
   * @generated from field: common.NetIPPort last_used_endpoint = 7;
   */
  lastUsedEndpoint?: NetIPPort;

  /**
   * @generated from field: google.protobuf.Timestamp last_endpoint_change = 8;
   */
  lastEndpointChange?: Timestamp;
};

/**
 * Describes the message talos.resource.definitions.kubespan.PeerStatusSpec.
 * Use `create(PeerStatusSpecSchema)` to create a new message.
 */
export const PeerStatusSpecSchema: GenMessage<PeerStatusSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_kubespan_kubespan, 4);

