// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file resource/definitions/siderolink/siderolink.proto (package talos.resource.definitions.siderolink, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { NetIPPort } from "../../../common/common_pb";
import { file_common_common } from "../../../common/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file resource/definitions/siderolink/siderolink.proto.
 */
export const file_resource_definitions_siderolink_siderolink: GenFile = /*@__PURE__*/
  fileDesc("CjByZXNvdXJjZS9kZWZpbml0aW9ucy9zaWRlcm9saW5rL3NpZGVyb2xpbmsucHJvdG8SJXRhbG9zLnJlc291cmNlLmRlZmluaXRpb25zLnNpZGVyb2xpbmsiZgoKQ29uZmlnU3BlYxIUCgxhcGlfZW5kcG9pbnQYASABKAkSDAoEaG9zdBgCIAEoCRISCgpqb2luX3Rva2VuGAMgASgJEhAKCGluc2VjdXJlGAQgASgIEg4KBnR1bm5lbBgFIAEoCCItCgpTdGF0dXNTcGVjEgwKBGhvc3QYASABKAkSEQoJY29ubmVjdGVkGAIgASgIImsKClR1bm5lbFNwZWMSFAoMYXBpX2VuZHBvaW50GAEgASgJEhEKCWxpbmtfbmFtZRgCIAEoCRILCgNtdHUYAyABKAMSJwoMbm9kZV9hZGRyZXNzGAQgASgLMhEuY29tbW9uLk5ldElQUG9ydEJ+Ci1kZXYudGFsb3MuYXBpLnJlc291cmNlLmRlZmluaXRpb25zLnNpZGVyb2xpbmtaTWdpdGh1Yi5jb20vc2lkZXJvbGFicy90YWxvcy9wa2cvbWFjaGluZXJ5L2FwaS9yZXNvdXJjZS9kZWZpbml0aW9ucy9zaWRlcm9saW5rYgZwcm90bzM", [file_common_common]);

/**
 * ConfigSpec describes Siderolink configuration.
 *
 * @generated from message talos.resource.definitions.siderolink.ConfigSpec
 */
export type ConfigSpec = Message<"talos.resource.definitions.siderolink.ConfigSpec"> & {
  /**
   * @generated from field: string api_endpoint = 1;
   */
  apiEndpoint: string;

  /**
   * @generated from field: string host = 2;
   */
  host: string;

  /**
   * @generated from field: string join_token = 3;
   */
  joinToken: string;

  /**
   * @generated from field: bool insecure = 4;
   */
  insecure: boolean;

  /**
   * @generated from field: bool tunnel = 5;
   */
  tunnel: boolean;
};

/**
 * Describes the message talos.resource.definitions.siderolink.ConfigSpec.
 * Use `create(ConfigSpecSchema)` to create a new message.
 */
export const ConfigSpecSchema: GenMessage<ConfigSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_siderolink_siderolink, 0);

/**
 * StatusSpec describes Siderolink status.
 *
 * @generated from message talos.resource.definitions.siderolink.StatusSpec
 */
export type StatusSpec = Message<"talos.resource.definitions.siderolink.StatusSpec"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * @generated from field: bool connected = 2;
   */
  connected: boolean;
};

/**
 * Describes the message talos.resource.definitions.siderolink.StatusSpec.
 * Use `create(StatusSpecSchema)` to create a new message.
 */
export const StatusSpecSchema: GenMessage<StatusSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_siderolink_siderolink, 1);

/**
 * TunnelSpec describes Siderolink GRPC Tunnel configuration.
 *
 * @generated from message talos.resource.definitions.siderolink.TunnelSpec
 */
export type TunnelSpec = Message<"talos.resource.definitions.siderolink.TunnelSpec"> & {
  /**
   * @generated from field: string api_endpoint = 1;
   */
  apiEndpoint: string;

  /**
   * @generated from field: string link_name = 2;
   */
  linkName: string;

  /**
   * @generated from field: int64 mtu = 3;
   */
  mtu: bigint;

  /**
   * @generated from field: common.NetIPPort node_address = 4;
   */
  nodeAddress?: NetIPPort;
};

/**
 * Describes the message talos.resource.definitions.siderolink.TunnelSpec.
 * Use `create(TunnelSpecSchema)` to create a new message.
 */
export const TunnelSpecSchema: GenMessage<TunnelSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_siderolink_siderolink, 2);

