// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file security/security.proto (package securityapi, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file security/security.proto.
 */
export const file_security_security: GenFile = /*@__PURE__*/
  fileDesc("ChdzZWN1cml0eS9zZWN1cml0eS5wcm90bxILc2VjdXJpdHlhcGkiIQoSQ2VydGlmaWNhdGVSZXF1ZXN0EgsKA2NzchgBIAEoDCIuChNDZXJ0aWZpY2F0ZVJlc3BvbnNlEgoKAmNhGAEgASgMEgsKA2NydBgCIAEoDDJjCg9TZWN1cml0eVNlcnZpY2USUAoLQ2VydGlmaWNhdGUSHy5zZWN1cml0eWFwaS5DZXJ0aWZpY2F0ZVJlcXVlc3QaIC5zZWN1cml0eWFwaS5DZXJ0aWZpY2F0ZVJlc3BvbnNlQlAKFmRldi50YWxvcy5hcGkuc2VjdXJpdHlaNmdpdGh1Yi5jb20vc2lkZXJvbGFicy90YWxvcy9wa2cvbWFjaGluZXJ5L2FwaS9zZWN1cml0eWIGcHJvdG8z");

/**
 * The request message containing the certificate signing request.
 *
 * @generated from message securityapi.CertificateRequest
 */
export type CertificateRequest = Message<"securityapi.CertificateRequest"> & {
  /**
   * Certificate Signing Request in PEM format.
   *
   * @generated from field: bytes csr = 1;
   */
  csr: Uint8Array;
};

/**
 * Describes the message securityapi.CertificateRequest.
 * Use `create(CertificateRequestSchema)` to create a new message.
 */
export const CertificateRequestSchema: GenMessage<CertificateRequest> = /*@__PURE__*/
  messageDesc(file_security_security, 0);

/**
 * The response message containing signed certificate.
 *
 * @generated from message securityapi.CertificateResponse
 */
export type CertificateResponse = Message<"securityapi.CertificateResponse"> & {
  /**
   * Certificate of the CA that signed the requested certificate in PEM format.
   *
   * @generated from field: bytes ca = 1;
   */
  ca: Uint8Array;

  /**
   * Signed X.509 requested certificate in PEM format.
   *
   * @generated from field: bytes crt = 2;
   */
  crt: Uint8Array;
};

/**
 * Describes the message securityapi.CertificateResponse.
 * Use `create(CertificateResponseSchema)` to create a new message.
 */
export const CertificateResponseSchema: GenMessage<CertificateResponse> = /*@__PURE__*/
  messageDesc(file_security_security, 1);

/**
 * The security service definition.
 *
 * @generated from service securityapi.SecurityService
 */
export const SecurityService: GenService<{
  /**
   * @generated from rpc securityapi.SecurityService.Certificate
   */
  certificate: {
    methodKind: "unary";
    input: typeof CertificateRequestSchema;
    output: typeof CertificateResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_security_security, 0);

