// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file resource/definitions/time/time.proto (package talos.resource.definitions.time, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file resource/definitions/time/time.proto.
 */
export const file_resource_definitions_time_time: GenFile = /*@__PURE__*/
  fileDesc("CiRyZXNvdXJjZS9kZWZpbml0aW9ucy90aW1lL3RpbWUucHJvdG8SH3RhbG9zLnJlc291cmNlLmRlZmluaXRpb25zLnRpbWUihAIKEUFkanRpbWVTdGF0dXNTcGVjEikKBm9mZnNldBgBIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbhIiChpmcmVxdWVuY3lfYWRqdXN0bWVudF9yYXRpbxgCIAEoARIsCgltYXhfZXJyb3IYAyABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb24SLAoJZXN0X2Vycm9yGAQgASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uEg4KBnN0YXR1cxgFIAEoCRIQCghjb25zdGFudBgGIAEoAxITCgtzeW5jX3N0YXR1cxgHIAEoCBINCgVzdGF0ZRgIIAEoCSJCCgpTdGF0dXNTcGVjEg4KBnN5bmNlZBgBIAEoCBINCgVlcG9jaBgCIAEoAxIVCg1zeW5jX2Rpc2FibGVkGAMgASgIQnIKJ2Rldi50YWxvcy5hcGkucmVzb3VyY2UuZGVmaW5pdGlvbnMudGltZVpHZ2l0aHViLmNvbS9zaWRlcm9sYWJzL3RhbG9zL3BrZy9tYWNoaW5lcnkvYXBpL3Jlc291cmNlL2RlZmluaXRpb25zL3RpbWViBnByb3RvMw", [file_google_protobuf_duration]);

/**
 * AdjtimeStatusSpec describes Linux internal adjtime state.
 *
 * @generated from message talos.resource.definitions.time.AdjtimeStatusSpec
 */
export type AdjtimeStatusSpec = Message<"talos.resource.definitions.time.AdjtimeStatusSpec"> & {
  /**
   * @generated from field: google.protobuf.Duration offset = 1;
   */
  offset?: Duration;

  /**
   * @generated from field: double frequency_adjustment_ratio = 2;
   */
  frequencyAdjustmentRatio: number;

  /**
   * @generated from field: google.protobuf.Duration max_error = 3;
   */
  maxError?: Duration;

  /**
   * @generated from field: google.protobuf.Duration est_error = 4;
   */
  estError?: Duration;

  /**
   * @generated from field: string status = 5;
   */
  status: string;

  /**
   * @generated from field: int64 constant = 6;
   */
  constant: bigint;

  /**
   * @generated from field: bool sync_status = 7;
   */
  syncStatus: boolean;

  /**
   * @generated from field: string state = 8;
   */
  state: string;
};

/**
 * Describes the message talos.resource.definitions.time.AdjtimeStatusSpec.
 * Use `create(AdjtimeStatusSpecSchema)` to create a new message.
 */
export const AdjtimeStatusSpecSchema: GenMessage<AdjtimeStatusSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_time_time, 0);

/**
 * StatusSpec describes time sync state.
 *
 * @generated from message talos.resource.definitions.time.StatusSpec
 */
export type StatusSpec = Message<"talos.resource.definitions.time.StatusSpec"> & {
  /**
   * @generated from field: bool synced = 1;
   */
  synced: boolean;

  /**
   * @generated from field: int64 epoch = 2;
   */
  epoch: bigint;

  /**
   * @generated from field: bool sync_disabled = 3;
   */
  syncDisabled: boolean;
};

/**
 * Describes the message talos.resource.definitions.time.StatusSpec.
 * Use `create(StatusSpecSchema)` to create a new message.
 */
export const StatusSpecSchema: GenMessage<StatusSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_time_time, 1);

