// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file resource/definitions/cluster/cluster.proto (package talos.resource.definitions.cluster, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { NetIP, NetIPPort, NetIPPrefix } from "../../../common/common_pb";
import { file_common_common } from "../../../common/common_pb";
import type { MachineType } from "../enums/enums_pb";
import { file_resource_definitions_enums_enums } from "../enums/enums_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file resource/definitions/cluster/cluster.proto.
 */
export const file_resource_definitions_cluster_cluster: GenFile = /*@__PURE__*/
  fileDesc("CipyZXNvdXJjZS9kZWZpbml0aW9ucy9jbHVzdGVyL2NsdXN0ZXIucHJvdG8SInRhbG9zLnJlc291cmNlLmRlZmluaXRpb25zLmNsdXN0ZXIi3AIKDUFmZmlsaWF0ZVNwZWMSDwoHbm9kZV9pZBgBIAEoCRIgCglhZGRyZXNzZXMYAiADKAsyDS5jb21tb24uTmV0SVASEAoIaG9zdG5hbWUYAyABKAkSEAoIbm9kZW5hbWUYBCABKAkSGAoQb3BlcmF0aW5nX3N5c3RlbRgFIAEoCRJDCgxtYWNoaW5lX3R5cGUYBiABKA4yLS50YWxvcy5yZXNvdXJjZS5kZWZpbml0aW9ucy5lbnVtcy5NYWNoaW5lVHlwZRJMCglrdWJlX3NwYW4YByABKAsyOS50YWxvcy5yZXNvdXJjZS5kZWZpbml0aW9ucy5jbHVzdGVyLkt1YmVTcGFuQWZmaWxpYXRlU3BlYxJHCg1jb250cm9sX3BsYW5lGAggASgLMjAudGFsb3MucmVzb3VyY2UuZGVmaW5pdGlvbnMuY2x1c3Rlci5Db250cm9sUGxhbmUi5wEKCkNvbmZpZ1NwZWMSGQoRZGlzY292ZXJ5X2VuYWJsZWQYASABKAgSIwobcmVnaXN0cnlfa3ViZXJuZXRlc19lbmFibGVkGAIgASgIEiAKGHJlZ2lzdHJ5X3NlcnZpY2VfZW5hYmxlZBgDIAEoCBIYChBzZXJ2aWNlX2VuZHBvaW50GAQgASgJEiEKGXNlcnZpY2VfZW5kcG9pbnRfaW5zZWN1cmUYBSABKAgSHgoWc2VydmljZV9lbmNyeXB0aW9uX2tleRgGIAEoDBIaChJzZXJ2aWNlX2NsdXN0ZXJfaWQYByABKAkiJwoMQ29udHJvbFBsYW5lEhcKD2FwaV9zZXJ2ZXJfcG9ydBgBIAEoAyIfCgxJZGVudGl0eVNwZWMSDwoHbm9kZV9pZBgBIAEoCSI0CghJbmZvU3BlYxISCgpjbHVzdGVyX2lkGAEgASgJEhQKDGNsdXN0ZXJfbmFtZRgCIAEoCSKkAQoVS3ViZVNwYW5BZmZpbGlhdGVTcGVjEhIKCnB1YmxpY19rZXkYASABKAkSHgoHYWRkcmVzcxgCIAEoCzINLmNvbW1vbi5OZXRJUBIxChRhZGRpdGlvbmFsX2FkZHJlc3NlcxgDIAMoCzITLmNvbW1vbi5OZXRJUFByZWZpeBIkCgllbmRwb2ludHMYBCADKAsyES5jb21tb24uTmV0SVBQb3J0IvkBCgpNZW1iZXJTcGVjEg8KB25vZGVfaWQYASABKAkSIAoJYWRkcmVzc2VzGAIgAygLMg0uY29tbW9uLk5ldElQEhAKCGhvc3RuYW1lGAMgASgJEkMKDG1hY2hpbmVfdHlwZRgEIAEoDjItLnRhbG9zLnJlc291cmNlLmRlZmluaXRpb25zLmVudW1zLk1hY2hpbmVUeXBlEhgKEG9wZXJhdGluZ19zeXN0ZW0YBSABKAkSRwoNY29udHJvbF9wbGFuZRgGIAEoCzIwLnRhbG9zLnJlc291cmNlLmRlZmluaXRpb25zLmNsdXN0ZXIuQ29udHJvbFBsYW5lQngKKmRldi50YWxvcy5hcGkucmVzb3VyY2UuZGVmaW5pdGlvbnMuY2x1c3RlclpKZ2l0aHViLmNvbS9zaWRlcm9sYWJzL3RhbG9zL3BrZy9tYWNoaW5lcnkvYXBpL3Jlc291cmNlL2RlZmluaXRpb25zL2NsdXN0ZXJiBnByb3RvMw", [file_common_common, file_resource_definitions_enums_enums]);

/**
 * AffiliateSpec describes Affiliate state.
 *
 * @generated from message talos.resource.definitions.cluster.AffiliateSpec
 */
export type AffiliateSpec = Message<"talos.resource.definitions.cluster.AffiliateSpec"> & {
  /**
   * @generated from field: string node_id = 1;
   */
  nodeId: string;

  /**
   * @generated from field: repeated common.NetIP addresses = 2;
   */
  addresses: NetIP[];

  /**
   * @generated from field: string hostname = 3;
   */
  hostname: string;

  /**
   * @generated from field: string nodename = 4;
   */
  nodename: string;

  /**
   * @generated from field: string operating_system = 5;
   */
  operatingSystem: string;

  /**
   * @generated from field: talos.resource.definitions.enums.MachineType machine_type = 6;
   */
  machineType: MachineType;

  /**
   * @generated from field: talos.resource.definitions.cluster.KubeSpanAffiliateSpec kube_span = 7;
   */
  kubeSpan?: KubeSpanAffiliateSpec;

  /**
   * @generated from field: talos.resource.definitions.cluster.ControlPlane control_plane = 8;
   */
  controlPlane?: ControlPlane;
};

/**
 * Describes the message talos.resource.definitions.cluster.AffiliateSpec.
 * Use `create(AffiliateSpecSchema)` to create a new message.
 */
export const AffiliateSpecSchema: GenMessage<AffiliateSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_cluster_cluster, 0);

/**
 * ConfigSpec describes KubeSpan configuration.
 *
 * @generated from message talos.resource.definitions.cluster.ConfigSpec
 */
export type ConfigSpec = Message<"talos.resource.definitions.cluster.ConfigSpec"> & {
  /**
   * @generated from field: bool discovery_enabled = 1;
   */
  discoveryEnabled: boolean;

  /**
   * @generated from field: bool registry_kubernetes_enabled = 2;
   */
  registryKubernetesEnabled: boolean;

  /**
   * @generated from field: bool registry_service_enabled = 3;
   */
  registryServiceEnabled: boolean;

  /**
   * @generated from field: string service_endpoint = 4;
   */
  serviceEndpoint: string;

  /**
   * @generated from field: bool service_endpoint_insecure = 5;
   */
  serviceEndpointInsecure: boolean;

  /**
   * @generated from field: bytes service_encryption_key = 6;
   */
  serviceEncryptionKey: Uint8Array;

  /**
   * @generated from field: string service_cluster_id = 7;
   */
  serviceClusterId: string;
};

/**
 * Describes the message talos.resource.definitions.cluster.ConfigSpec.
 * Use `create(ConfigSpecSchema)` to create a new message.
 */
export const ConfigSpecSchema: GenMessage<ConfigSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_cluster_cluster, 1);

/**
 * ControlPlane describes ControlPlane data if any.
 *
 * @generated from message talos.resource.definitions.cluster.ControlPlane
 */
export type ControlPlane = Message<"talos.resource.definitions.cluster.ControlPlane"> & {
  /**
   * @generated from field: int64 api_server_port = 1;
   */
  apiServerPort: bigint;
};

/**
 * Describes the message talos.resource.definitions.cluster.ControlPlane.
 * Use `create(ControlPlaneSchema)` to create a new message.
 */
export const ControlPlaneSchema: GenMessage<ControlPlane> = /*@__PURE__*/
  messageDesc(file_resource_definitions_cluster_cluster, 2);

/**
 * IdentitySpec describes status of rendered secrets.
 *
 * Note: IdentitySpec is persisted on disk in the STATE partition,
 * so YAML serialization should be kept backwards compatible.
 *
 * @generated from message talos.resource.definitions.cluster.IdentitySpec
 */
export type IdentitySpec = Message<"talos.resource.definitions.cluster.IdentitySpec"> & {
  /**
   * @generated from field: string node_id = 1;
   */
  nodeId: string;
};

/**
 * Describes the message talos.resource.definitions.cluster.IdentitySpec.
 * Use `create(IdentitySpecSchema)` to create a new message.
 */
export const IdentitySpecSchema: GenMessage<IdentitySpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_cluster_cluster, 3);

/**
 * InfoSpec describes cluster information.
 *
 * @generated from message talos.resource.definitions.cluster.InfoSpec
 */
export type InfoSpec = Message<"talos.resource.definitions.cluster.InfoSpec"> & {
  /**
   * @generated from field: string cluster_id = 1;
   */
  clusterId: string;

  /**
   * @generated from field: string cluster_name = 2;
   */
  clusterName: string;
};

/**
 * Describes the message talos.resource.definitions.cluster.InfoSpec.
 * Use `create(InfoSpecSchema)` to create a new message.
 */
export const InfoSpecSchema: GenMessage<InfoSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_cluster_cluster, 4);

/**
 * KubeSpanAffiliateSpec describes additional information specific for the KubeSpan.
 *
 * @generated from message talos.resource.definitions.cluster.KubeSpanAffiliateSpec
 */
export type KubeSpanAffiliateSpec = Message<"talos.resource.definitions.cluster.KubeSpanAffiliateSpec"> & {
  /**
   * @generated from field: string public_key = 1;
   */
  publicKey: string;

  /**
   * @generated from field: common.NetIP address = 2;
   */
  address?: NetIP;

  /**
   * @generated from field: repeated common.NetIPPrefix additional_addresses = 3;
   */
  additionalAddresses: NetIPPrefix[];

  /**
   * @generated from field: repeated common.NetIPPort endpoints = 4;
   */
  endpoints: NetIPPort[];
};

/**
 * Describes the message talos.resource.definitions.cluster.KubeSpanAffiliateSpec.
 * Use `create(KubeSpanAffiliateSpecSchema)` to create a new message.
 */
export const KubeSpanAffiliateSpecSchema: GenMessage<KubeSpanAffiliateSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_cluster_cluster, 5);

/**
 * MemberSpec describes Member state.
 *
 * @generated from message talos.resource.definitions.cluster.MemberSpec
 */
export type MemberSpec = Message<"talos.resource.definitions.cluster.MemberSpec"> & {
  /**
   * @generated from field: string node_id = 1;
   */
  nodeId: string;

  /**
   * @generated from field: repeated common.NetIP addresses = 2;
   */
  addresses: NetIP[];

  /**
   * @generated from field: string hostname = 3;
   */
  hostname: string;

  /**
   * @generated from field: talos.resource.definitions.enums.MachineType machine_type = 4;
   */
  machineType: MachineType;

  /**
   * @generated from field: string operating_system = 5;
   */
  operatingSystem: string;

  /**
   * @generated from field: talos.resource.definitions.cluster.ControlPlane control_plane = 6;
   */
  controlPlane?: ControlPlane;
};

/**
 * Describes the message talos.resource.definitions.cluster.MemberSpec.
 * Use `create(MemberSpecSchema)` to create a new message.
 */
export const MemberSpecSchema: GenMessage<MemberSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_cluster_cluster, 6);

