// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file resource/definitions/v1alpha1/v1alpha1.proto (package talos.resource.definitions.v1alpha1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file resource/definitions/v1alpha1/v1alpha1.proto.
 */
export const file_resource_definitions_v1alpha1_v1alpha1: GenFile = /*@__PURE__*/
  fileDesc("CixyZXNvdXJjZS9kZWZpbml0aW9ucy92MWFscGhhMS92MWFscGhhMS5wcm90bxIjdGFsb3MucmVzb3VyY2UuZGVmaW5pdGlvbnMudjFhbHBoYTEiQAoLU2VydmljZVNwZWMSDwoHcnVubmluZxgBIAEoCBIPCgdoZWFsdGh5GAIgASgIEg8KB3Vua25vd24YAyABKAhCegorZGV2LnRhbG9zLmFwaS5yZXNvdXJjZS5kZWZpbml0aW9ucy52MWFscGhhMVpLZ2l0aHViLmNvbS9zaWRlcm9sYWJzL3RhbG9zL3BrZy9tYWNoaW5lcnkvYXBpL3Jlc291cmNlL2RlZmluaXRpb25zL3YxYWxwaGExYgZwcm90bzM");

/**
 * ServiceSpec describe service state.
 *
 * @generated from message talos.resource.definitions.v1alpha1.ServiceSpec
 */
export type ServiceSpec = Message<"talos.resource.definitions.v1alpha1.ServiceSpec"> & {
  /**
   * @generated from field: bool running = 1;
   */
  running: boolean;

  /**
   * @generated from field: bool healthy = 2;
   */
  healthy: boolean;

  /**
   * @generated from field: bool unknown = 3;
   */
  unknown: boolean;
};

/**
 * Describes the message talos.resource.definitions.v1alpha1.ServiceSpec.
 * Use `create(ServiceSpecSchema)` to create a new message.
 */
export const ServiceSpecSchema: GenMessage<ServiceSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_v1alpha1_v1alpha1, 0);

