// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file resource/definitions/proto/proto.proto (package talos.resource.definitions.proto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file resource/definitions/proto/proto.proto.
 */
export const file_resource_definitions_proto_proto: GenFile = /*@__PURE__*/
  fileDesc("CiZyZXNvdXJjZS9kZWZpbml0aW9ucy9wcm90by9wcm90by5wcm90bxIgdGFsb3MucmVzb3VyY2UuZGVmaW5pdGlvbnMucHJvdG8iRQoOTGludXhJRE1hcHBpbmcSFAoMY29udGFpbmVyX2lkGAEgASgNEg8KB2hvc3RfaWQYAiABKA0SDAoEc2l6ZRgDIAEoDSLbAQoFTW91bnQSEwoLZGVzdGluYXRpb24YASABKAkSDAoEdHlwZRgCIAEoCRIOCgZzb3VyY2UYAyABKAkSDwoHb3B0aW9ucxgEIAMoCRJGCgx1aWRfbWFwcGluZ3MYBSADKAsyMC50YWxvcy5yZXNvdXJjZS5kZWZpbml0aW9ucy5wcm90by5MaW51eElETWFwcGluZxJGCgxnaWRfbWFwcGluZ3MYBiADKAsyMC50YWxvcy5yZXNvdXJjZS5kZWZpbml0aW9ucy5wcm90by5MaW51eElETWFwcGluZ0J0CihkZXYudGFsb3MuYXBpLnJlc291cmNlLmRlZmluaXRpb25zLnByb3RvWkhnaXRodWIuY29tL3NpZGVyb2xhYnMvdGFsb3MvcGtnL21hY2hpbmVyeS9hcGkvcmVzb3VyY2UvZGVmaW5pdGlvbnMvcHJvdG9iBnByb3RvMw");

/**
 * LinuxIDMapping specifies UID/GID mappings.
 *
 * @generated from message talos.resource.definitions.proto.LinuxIDMapping
 */
export type LinuxIDMapping = Message<"talos.resource.definitions.proto.LinuxIDMapping"> & {
  /**
   * @generated from field: uint32 container_id = 1;
   */
  containerId: number;

  /**
   * @generated from field: uint32 host_id = 2;
   */
  hostId: number;

  /**
   * @generated from field: uint32 size = 3;
   */
  size: number;
};

/**
 * Describes the message talos.resource.definitions.proto.LinuxIDMapping.
 * Use `create(LinuxIDMappingSchema)` to create a new message.
 */
export const LinuxIDMappingSchema: GenMessage<LinuxIDMapping> = /*@__PURE__*/
  messageDesc(file_resource_definitions_proto_proto, 0);

/**
 * Mount specifies a mount for a container.
 *
 * @generated from message talos.resource.definitions.proto.Mount
 */
export type Mount = Message<"talos.resource.definitions.proto.Mount"> & {
  /**
   * @generated from field: string destination = 1;
   */
  destination: string;

  /**
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * @generated from field: string source = 3;
   */
  source: string;

  /**
   * @generated from field: repeated string options = 4;
   */
  options: string[];

  /**
   * @generated from field: repeated talos.resource.definitions.proto.LinuxIDMapping uid_mappings = 5;
   */
  uidMappings: LinuxIDMapping[];

  /**
   * @generated from field: repeated talos.resource.definitions.proto.LinuxIDMapping gid_mappings = 6;
   */
  gidMappings: LinuxIDMapping[];
};

/**
 * Describes the message talos.resource.definitions.proto.Mount.
 * Use `create(MountSchema)` to create a new message.
 */
export const MountSchema: GenMessage<Mount> = /*@__PURE__*/
  messageDesc(file_resource_definitions_proto_proto, 1);

