// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file resource/definitions/kubeaccess/kubeaccess.proto (package talos.resource.definitions.kubeaccess, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file resource/definitions/kubeaccess/kubeaccess.proto.
 */
export const file_resource_definitions_kubeaccess_kubeaccess: GenFile = /*@__PURE__*/
  fileDesc("CjByZXNvdXJjZS9kZWZpbml0aW9ucy9rdWJlYWNjZXNzL2t1YmVhY2Nlc3MucHJvdG8SJXRhbG9zLnJlc291cmNlLmRlZmluaXRpb25zLmt1YmVhY2Nlc3MiXwoKQ29uZmlnU3BlYxIPCgdlbmFibGVkGAEgASgIEhkKEWFsbG93ZWRfYXBpX3JvbGVzGAIgAygJEiUKHWFsbG93ZWRfa3ViZXJuZXRlc19uYW1lc3BhY2VzGAMgAygJQn4KLWRldi50YWxvcy5hcGkucmVzb3VyY2UuZGVmaW5pdGlvbnMua3ViZWFjY2Vzc1pNZ2l0aHViLmNvbS9zaWRlcm9sYWJzL3RhbG9zL3BrZy9tYWNoaW5lcnkvYXBpL3Jlc291cmNlL2RlZmluaXRpb25zL2t1YmVhY2Nlc3NiBnByb3RvMw");

/**
 * ConfigSpec describes KubeSpan configuration..
 *
 * @generated from message talos.resource.definitions.kubeaccess.ConfigSpec
 */
export type ConfigSpec = Message<"talos.resource.definitions.kubeaccess.ConfigSpec"> & {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;

  /**
   * @generated from field: repeated string allowed_api_roles = 2;
   */
  allowedApiRoles: string[];

  /**
   * @generated from field: repeated string allowed_kubernetes_namespaces = 3;
   */
  allowedKubernetesNamespaces: string[];
};

/**
 * Describes the message talos.resource.definitions.kubeaccess.ConfigSpec.
 * Use `create(ConfigSpecSchema)` to create a new message.
 */
export const ConfigSpecSchema: GenMessage<ConfigSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_kubeaccess_kubeaccess, 0);

