// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file cluster/cluster.proto (package cluster, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Metadata } from "../common/common_pb";
import { file_common_common } from "../common/common_pb";
import type { Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cluster/cluster.proto.
 */
export const file_cluster_cluster: GenFile = /*@__PURE__*/
  fileDesc("ChVjbHVzdGVyL2NsdXN0ZXIucHJvdG8SB2NsdXN0ZXIicQoSSGVhbHRoQ2hlY2tSZXF1ZXN0Ei8KDHdhaXRfdGltZW91dBgBIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbhIqCgxjbHVzdGVyX2luZm8YAiABKAsyFC5jbHVzdGVyLkNsdXN0ZXJJbmZvIlgKC0NsdXN0ZXJJbmZvEhsKE2NvbnRyb2xfcGxhbmVfbm9kZXMYASADKAkSFAoMd29ya2VyX25vZGVzGAIgAygJEhYKDmZvcmNlX2VuZHBvaW50GAMgASgJIkoKE0hlYWx0aENoZWNrUHJvZ3Jlc3MSIgoIbWV0YWRhdGEYASABKAsyEC5jb21tb24uTWV0YWRhdGESDwoHbWVzc2FnZRgCIAEoCTJcCg5DbHVzdGVyU2VydmljZRJKCgtIZWFsdGhDaGVjaxIbLmNsdXN0ZXIuSGVhbHRoQ2hlY2tSZXF1ZXN0GhwuY2x1c3Rlci5IZWFsdGhDaGVja1Byb2dyZXNzMAFCTgoVZGV2LnRhbG9zLmFwaS5jbHVzdGVyWjVnaXRodWIuY29tL3NpZGVyb2xhYnMvdGFsb3MvcGtnL21hY2hpbmVyeS9hcGkvY2x1c3RlcmIGcHJvdG8z", [file_common_common, file_google_protobuf_duration]);

/**
 * @generated from message cluster.HealthCheckRequest
 */
export type HealthCheckRequest = Message<"cluster.HealthCheckRequest"> & {
  /**
   * @generated from field: google.protobuf.Duration wait_timeout = 1;
   */
  waitTimeout?: Duration;

  /**
   * @generated from field: cluster.ClusterInfo cluster_info = 2;
   */
  clusterInfo?: ClusterInfo;
};

/**
 * Describes the message cluster.HealthCheckRequest.
 * Use `create(HealthCheckRequestSchema)` to create a new message.
 */
export const HealthCheckRequestSchema: GenMessage<HealthCheckRequest> = /*@__PURE__*/
  messageDesc(file_cluster_cluster, 0);

/**
 * @generated from message cluster.ClusterInfo
 */
export type ClusterInfo = Message<"cluster.ClusterInfo"> & {
  /**
   * @generated from field: repeated string control_plane_nodes = 1;
   */
  controlPlaneNodes: string[];

  /**
   * @generated from field: repeated string worker_nodes = 2;
   */
  workerNodes: string[];

  /**
   * @generated from field: string force_endpoint = 3;
   */
  forceEndpoint: string;
};

/**
 * Describes the message cluster.ClusterInfo.
 * Use `create(ClusterInfoSchema)` to create a new message.
 */
export const ClusterInfoSchema: GenMessage<ClusterInfo> = /*@__PURE__*/
  messageDesc(file_cluster_cluster, 1);

/**
 * @generated from message cluster.HealthCheckProgress
 */
export type HealthCheckProgress = Message<"cluster.HealthCheckProgress"> & {
  /**
   * @generated from field: common.Metadata metadata = 1;
   */
  metadata?: Metadata;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message cluster.HealthCheckProgress.
 * Use `create(HealthCheckProgressSchema)` to create a new message.
 */
export const HealthCheckProgressSchema: GenMessage<HealthCheckProgress> = /*@__PURE__*/
  messageDesc(file_cluster_cluster, 2);

/**
 * The cluster service definition.
 *
 * @generated from service cluster.ClusterService
 */
export const ClusterService: GenService<{
  /**
   * @generated from rpc cluster.ClusterService.HealthCheck
   */
  healthCheck: {
    methodKind: "server_streaming";
    input: typeof HealthCheckRequestSchema;
    output: typeof HealthCheckProgressSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_cluster_cluster, 0);

