// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file resource/config/config.proto (package resource.config, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file resource/config/config.proto.
 */
export const file_resource_config_config: GenFile = /*@__PURE__*/
  fileDesc("ChxyZXNvdXJjZS9jb25maWcvY29uZmlnLnByb3RvEg9yZXNvdXJjZS5jb25maWciLAoRTWFjaGluZUNvbmZpZ1NwZWMSFwoPeWFtbF9tYXJzaGFsbGVkGAEgASgMIkUKD01hY2hpbmVUeXBlU3BlYxIyCgxtYWNoaW5lX3R5cGUYASABKA4yHC5yZXNvdXJjZS5jb25maWcuTWFjaGluZVR5cGUqQwoLTWFjaGluZVR5cGUSCwoHVU5LTk9XThAAEggKBElOSVQQARIRCg1DT05UUk9MX1BMQU5FEAISCgoGV09SS0VSEANCXgodZGV2LnRhbG9zLmFwaS5yZXNvdXJjZS5jb25maWdaPWdpdGh1Yi5jb20vc2lkZXJvbGFicy90YWxvcy9wa2cvbWFjaGluZXJ5L2FwaS9yZXNvdXJjZS9jb25maWdiBnByb3RvMw");

/**
 * MessageConfigSpec is the spec for the config.MachineConfig resource.
 *
 * @generated from message resource.config.MachineConfigSpec
 */
export type MachineConfigSpec = Message<"resource.config.MachineConfigSpec"> & {
  /**
   * Contains YAML marshalled machine configuration.
   *
   * Byte representation is preserved as the machine configuration was submitted to the node.
   *
   * @generated from field: bytes yaml_marshalled = 1;
   */
  yamlMarshalled: Uint8Array;
};

/**
 * Describes the message resource.config.MachineConfigSpec.
 * Use `create(MachineConfigSpecSchema)` to create a new message.
 */
export const MachineConfigSpecSchema: GenMessage<MachineConfigSpec> = /*@__PURE__*/
  messageDesc(file_resource_config_config, 0);

/**
 * MachineTypeSpec is the spec for the config.MachineType resource.
 *
 * @generated from message resource.config.MachineTypeSpec
 */
export type MachineTypeSpec = Message<"resource.config.MachineTypeSpec"> & {
  /**
   * @generated from field: resource.config.MachineType machine_type = 1;
   */
  machineType: MachineType;
};

/**
 * Describes the message resource.config.MachineTypeSpec.
 * Use `create(MachineTypeSpecSchema)` to create a new message.
 */
export const MachineTypeSpecSchema: GenMessage<MachineTypeSpec> = /*@__PURE__*/
  messageDesc(file_resource_config_config, 1);

/**
 * MachineType matches machine.Type constants.
 *
 * @generated from enum resource.config.MachineType
 */
export enum MachineType {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: INIT = 1;
   */
  INIT = 1,

  /**
   * @generated from enum value: CONTROL_PLANE = 2;
   */
  CONTROL_PLANE = 2,

  /**
   * @generated from enum value: WORKER = 3;
   */
  WORKER = 3,
}

/**
 * Describes the enum resource.config.MachineType.
 */
export const MachineTypeSchema: GenEnum<MachineType> = /*@__PURE__*/
  enumDesc(file_resource_config_config, 0);

