// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file resource/definitions/files/files.proto (package talos.resource.definitions.files, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file resource/definitions/files/files.proto.
 */
export const file_resource_definitions_files_files: GenFile = /*@__PURE__*/
  fileDesc("CiZyZXNvdXJjZS9kZWZpbml0aW9ucy9maWxlcy9maWxlcy5wcm90bxIgdGFsb3MucmVzb3VyY2UuZGVmaW5pdGlvbnMuZmlsZXMiSAoPRXRjRmlsZVNwZWNTcGVjEhAKCGNvbnRlbnRzGAEgASgMEgwKBG1vZGUYAiABKA0SFQoNc2VsaW51eF9sYWJlbBgDIAEoCSIpChFFdGNGaWxlU3RhdHVzU3BlYxIUCgxzcGVjX3ZlcnNpb24YASABKAlCdAooZGV2LnRhbG9zLmFwaS5yZXNvdXJjZS5kZWZpbml0aW9ucy5maWxlc1pIZ2l0aHViLmNvbS9zaWRlcm9sYWJzL3RhbG9zL3BrZy9tYWNoaW5lcnkvYXBpL3Jlc291cmNlL2RlZmluaXRpb25zL2ZpbGVzYgZwcm90bzM");

/**
 * EtcFileSpecSpec describes status of rendered secrets.
 *
 * @generated from message talos.resource.definitions.files.EtcFileSpecSpec
 */
export type EtcFileSpecSpec = Message<"talos.resource.definitions.files.EtcFileSpecSpec"> & {
  /**
   * @generated from field: bytes contents = 1;
   */
  contents: Uint8Array;

  /**
   * @generated from field: uint32 mode = 2;
   */
  mode: number;

  /**
   * @generated from field: string selinux_label = 3;
   */
  selinuxLabel: string;
};

/**
 * Describes the message talos.resource.definitions.files.EtcFileSpecSpec.
 * Use `create(EtcFileSpecSpecSchema)` to create a new message.
 */
export const EtcFileSpecSpecSchema: GenMessage<EtcFileSpecSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_files_files, 0);

/**
 * EtcFileStatusSpec describes status of rendered secrets.
 *
 * @generated from message talos.resource.definitions.files.EtcFileStatusSpec
 */
export type EtcFileStatusSpec = Message<"talos.resource.definitions.files.EtcFileStatusSpec"> & {
  /**
   * @generated from field: string spec_version = 1;
   */
  specVersion: string;
};

/**
 * Describes the message talos.resource.definitions.files.EtcFileStatusSpec.
 * Use `create(EtcFileStatusSpecSchema)` to create a new message.
 */
export const EtcFileStatusSpecSchema: GenMessage<EtcFileStatusSpec> = /*@__PURE__*/
  messageDesc(file_resource_definitions_files_files, 1);

