// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file time/time.proto (package time, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Metadata } from "../common/common_pb";
import { file_common_common } from "../common/common_pb";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file time/time.proto.
 */
export const file_time_time: GenFile = /*@__PURE__*/
  fileDesc("Cg90aW1lL3RpbWUucHJvdG8SBHRpbWUiHQoLVGltZVJlcXVlc3QSDgoGc2VydmVyGAEgASgJIpkBCgRUaW1lEiIKCG1ldGFkYXRhGAEgASgLMhAuY29tbW9uLk1ldGFkYXRhEg4KBnNlcnZlchgCIAEoCRItCglsb2NhbHRpbWUYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnJlbW90ZXRpbWUYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIiwKDFRpbWVSZXNwb25zZRIcCghtZXNzYWdlcxgBIAMoCzIKLnRpbWUuVGltZTJ1CgtUaW1lU2VydmljZRIyCgRUaW1lEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhIudGltZS5UaW1lUmVzcG9uc2USMgoJVGltZUNoZWNrEhEudGltZS5UaW1lUmVxdWVzdBoSLnRpbWUuVGltZVJlc3BvbnNlQkgKEmRldi50YWxvcy5hcGkudGltZVoyZ2l0aHViLmNvbS9zaWRlcm9sYWJzL3RhbG9zL3BrZy9tYWNoaW5lcnkvYXBpL3RpbWViBnByb3RvMw", [file_common_common, file_google_protobuf_empty, file_google_protobuf_timestamp]);

/**
 * The response message containing the ntp server
 *
 * @generated from message time.TimeRequest
 */
export type TimeRequest = Message<"time.TimeRequest"> & {
  /**
   * @generated from field: string server = 1;
   */
  server: string;
};

/**
 * Describes the message time.TimeRequest.
 * Use `create(TimeRequestSchema)` to create a new message.
 */
export const TimeRequestSchema: GenMessage<TimeRequest> = /*@__PURE__*/
  messageDesc(file_time_time, 0);

/**
 * @generated from message time.Time
 */
export type Time = Message<"time.Time"> & {
  /**
   * @generated from field: common.Metadata metadata = 1;
   */
  metadata?: Metadata;

  /**
   * @generated from field: string server = 2;
   */
  server: string;

  /**
   * @generated from field: google.protobuf.Timestamp localtime = 3;
   */
  localtime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp remotetime = 4;
   */
  remotetime?: Timestamp;
};

/**
 * Describes the message time.Time.
 * Use `create(TimeSchema)` to create a new message.
 */
export const TimeSchema: GenMessage<Time> = /*@__PURE__*/
  messageDesc(file_time_time, 1);

/**
 * The response message containing the ntp server, time, and offset
 *
 * @generated from message time.TimeResponse
 */
export type TimeResponse = Message<"time.TimeResponse"> & {
  /**
   * @generated from field: repeated time.Time messages = 1;
   */
  messages: Time[];
};

/**
 * Describes the message time.TimeResponse.
 * Use `create(TimeResponseSchema)` to create a new message.
 */
export const TimeResponseSchema: GenMessage<TimeResponse> = /*@__PURE__*/
  messageDesc(file_time_time, 2);

/**
 * The time service definition.
 *
 * @generated from service time.TimeService
 */
export const TimeService: GenService<{
  /**
   * @generated from rpc time.TimeService.Time
   */
  time: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof TimeResponseSchema;
  },
  /**
   * @generated from rpc time.TimeService.TimeCheck
   */
  timeCheck: {
    methodKind: "unary";
    input: typeof TimeRequestSchema;
    output: typeof TimeResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_time_time, 0);

