// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file inspect/inspect.proto (package inspect, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Metadata } from "../common/common_pb";
import { file_common_common } from "../common/common_pb";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file inspect/inspect.proto.
 */
export const file_inspect_inspect: GenFile = /*@__PURE__*/
  fileDesc("ChVpbnNwZWN0L2luc3BlY3QucHJvdG8SB2luc3BlY3QicwobQ29udHJvbGxlclJ1bnRpbWVEZXBlbmRlbmN5EiIKCG1ldGFkYXRhGAEgASgLMhAuY29tbW9uLk1ldGFkYXRhEjAKBWVkZ2VzGAIgAygLMiEuaW5zcGVjdC5Db250cm9sbGVyRGVwZW5kZW5jeUVkZ2UiXwolQ29udHJvbGxlclJ1bnRpbWVEZXBlbmRlbmNpZXNSZXNwb25zZRI2CghtZXNzYWdlcxgBIAMoCzIkLmluc3BlY3QuQ29udHJvbGxlclJ1bnRpbWVEZXBlbmRlbmN5IqsBChhDb250cm9sbGVyRGVwZW5kZW5jeUVkZ2USFwoPY29udHJvbGxlcl9uYW1lGAEgASgJEi4KCWVkZ2VfdHlwZRgCIAEoDjIbLmluc3BlY3QuRGVwZW5kZW5jeUVkZ2VUeXBlEhoKEnJlc291cmNlX25hbWVzcGFjZRgDIAEoCRIVCg1yZXNvdXJjZV90eXBlGAQgASgJEhMKC3Jlc291cmNlX2lkGAUgASgJKngKEkRlcGVuZGVuY3lFZGdlVHlwZRIUChBPVVRQVVRfRVhDTFVTSVZFEAASEQoNT1VUUFVUX1NIQVJFRBADEhAKDElOUFVUX1NUUk9ORxABEg4KCklOUFVUX1dFQUsQAhIXChNJTlBVVF9ERVNUUk9ZX1JFQURZEAQyeQoOSW5zcGVjdFNlcnZpY2USZwodQ29udHJvbGxlclJ1bnRpbWVEZXBlbmRlbmNpZXMSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaLi5pbnNwZWN0LkNvbnRyb2xsZXJSdW50aW1lRGVwZW5kZW5jaWVzUmVzcG9uc2VCTgoVZGV2LnRhbG9zLmFwaS5pbnNwZWN0WjVnaXRodWIuY29tL3NpZGVyb2xhYnMvdGFsb3MvcGtnL21hY2hpbmVyeS9hcGkvaW5zcGVjdGIGcHJvdG8z", [file_common_common, file_google_protobuf_empty]);

/**
 * The ControllerRuntimeDependency message contains the graph of controller-resource dependencies.
 *
 * @generated from message inspect.ControllerRuntimeDependency
 */
export type ControllerRuntimeDependency = Message<"inspect.ControllerRuntimeDependency"> & {
  /**
   * @generated from field: common.Metadata metadata = 1;
   */
  metadata?: Metadata;

  /**
   * @generated from field: repeated inspect.ControllerDependencyEdge edges = 2;
   */
  edges: ControllerDependencyEdge[];
};

/**
 * Describes the message inspect.ControllerRuntimeDependency.
 * Use `create(ControllerRuntimeDependencySchema)` to create a new message.
 */
export const ControllerRuntimeDependencySchema: GenMessage<ControllerRuntimeDependency> = /*@__PURE__*/
  messageDesc(file_inspect_inspect, 0);

/**
 * @generated from message inspect.ControllerRuntimeDependenciesResponse
 */
export type ControllerRuntimeDependenciesResponse = Message<"inspect.ControllerRuntimeDependenciesResponse"> & {
  /**
   * @generated from field: repeated inspect.ControllerRuntimeDependency messages = 1;
   */
  messages: ControllerRuntimeDependency[];
};

/**
 * Describes the message inspect.ControllerRuntimeDependenciesResponse.
 * Use `create(ControllerRuntimeDependenciesResponseSchema)` to create a new message.
 */
export const ControllerRuntimeDependenciesResponseSchema: GenMessage<ControllerRuntimeDependenciesResponse> = /*@__PURE__*/
  messageDesc(file_inspect_inspect, 1);

/**
 * @generated from message inspect.ControllerDependencyEdge
 */
export type ControllerDependencyEdge = Message<"inspect.ControllerDependencyEdge"> & {
  /**
   * @generated from field: string controller_name = 1;
   */
  controllerName: string;

  /**
   * @generated from field: inspect.DependencyEdgeType edge_type = 2;
   */
  edgeType: DependencyEdgeType;

  /**
   * @generated from field: string resource_namespace = 3;
   */
  resourceNamespace: string;

  /**
   * @generated from field: string resource_type = 4;
   */
  resourceType: string;

  /**
   * @generated from field: string resource_id = 5;
   */
  resourceId: string;
};

/**
 * Describes the message inspect.ControllerDependencyEdge.
 * Use `create(ControllerDependencyEdgeSchema)` to create a new message.
 */
export const ControllerDependencyEdgeSchema: GenMessage<ControllerDependencyEdge> = /*@__PURE__*/
  messageDesc(file_inspect_inspect, 2);

/**
 * @generated from enum inspect.DependencyEdgeType
 */
export enum DependencyEdgeType {
  /**
   * @generated from enum value: OUTPUT_EXCLUSIVE = 0;
   */
  OUTPUT_EXCLUSIVE = 0,

  /**
   * @generated from enum value: OUTPUT_SHARED = 3;
   */
  OUTPUT_SHARED = 3,

  /**
   * @generated from enum value: INPUT_STRONG = 1;
   */
  INPUT_STRONG = 1,

  /**
   * @generated from enum value: INPUT_WEAK = 2;
   */
  INPUT_WEAK = 2,

  /**
   * @generated from enum value: INPUT_DESTROY_READY = 4;
   */
  INPUT_DESTROY_READY = 4,
}

/**
 * Describes the enum inspect.DependencyEdgeType.
 */
export const DependencyEdgeTypeSchema: GenEnum<DependencyEdgeType> = /*@__PURE__*/
  enumDesc(file_inspect_inspect, 0);

/**
 * The inspect service definition.
 *
 * InspectService provides auxiliary API to inspect OS internals.
 *
 * @generated from service inspect.InspectService
 */
export const InspectService: GenService<{
  /**
   * @generated from rpc inspect.InspectService.ControllerRuntimeDependencies
   */
  controllerRuntimeDependencies: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof ControllerRuntimeDependenciesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_inspect_inspect, 0);

